server:
  port: 8080

---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.default.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: reservation
          destination: msateam
          contentType: application/json
        event-out:
          destination: msateam
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8083

feign:
  hystrix:
    enabled: true

hystrix:
  command: 
    #전역설정
      default:
        execution.isolation.thread.timeoutInMilliseconds: 1

---

spring:
  profiles: docker
  sleuth:
    propagation-keys: x-request-id,x-ot-span-context
    propagation:
      type: B3,W3C
  opentracing:
    enabled: true
  zipkin:
    base-url: http://jaeger-collector.default.svc.cluster.local:9411
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.default.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: reservation
          destination: msateam
          contentType: application/json
        event-out:
          destination: msateam
          contentType: application/json
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
